### ISSUE TITLE
an error I saw during importing and parsing (insert edit stuff related)

### ISSUE THREAD

**Issue by dedan** [maebert/cnoms#14]
`127.0.0.1 - - [20/Oct/2012 09:51:24] "POST /import_website?user=localuser&path_to_site=tests%2Ftest_website1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dedan/.virtualenvs/cnoms/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dedan/projects/cnoms/cnoms/server/server.py", line 75, in import_website
    template, for_db = parse_html(open(os.path.join(path_to_site, filename)).read(), user, sitename)
  File "/Users/dedan/projects/cnoms/cnoms/parser/parser.py", line 88, in parse_html
    insert_edit_fields(template)
  File "/Users/dedan/projects/cnoms/cnoms/parser/parser.py", line 80, in insert_edit_fields
    body.insert(-1, "{% if cnoms_edit %}{% include '/edit.jinja' %}{% else %}{% include '/edit_link.jinja' %}{% endif %}")
AttributeError: 'NoneType' object has no attribute 'insert'`

**Comment by maebert** [comment]
Are you sure you have a `<body>` element in your html?

**Comment by dedan** [comment]
hmm, ok. Don't know in which tired state I opened this pull request. Everything working now. Strange
